---
pipeline:
  build:
    image: debian
    commands:
      - apt-get update
      - apt-get install -y curl ca-certificates git
      # Install latest helm and unittest plugin
      - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
      - helm init -c
      - helm plugin install https://github.com/lrills/helm-unittest
      # Helm - lint, test and package
      - ./scripts/test
      - helm package -d ./charts/latest ./rancher
      # Pull and update Index 
      - curl -o /tmp/index.yaml https://releases.rancher.com/server-charts/latest/index.yaml
      - helm repo index --merge /tmp/index.yaml ./charts/latest

  publish:
    image: plugins/gcs
    source: charts/latest
    target: releases.rancher.com/server-charts/latest
    acl:
      - allUsers:READER
    cache_control: public,max-age=3600
    secrets:
      - source: google_auth_key
        target: GOOGLE_CREDENTIALS
    when:
      branch: master
      event: tag